description: 堀口の github.io
url: "https://Naoya-Horiguchi.github.io/index.html"
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
theme: jekyll-theme-cayman
author:
  name: Naoya Horiguchi
  twitter: nhoriguchi
